all: sendDataFifo recDataFifo mySendDataFifo myRecDataFifo

sendDataFifo: sendDataFifo.c
	gcc -o sendDataFifo sendDataFifo.c

recDataFifo: recDataFifo.c
	gcc -o recDataFifo recDataFifo.c

mySendDataFifo: mySendDataFifo.c
	gcc -o mySendDataFifo mySendDataFifo.c

myRecDataFifo: myRecDataFifo.c
	gcc -o myRecDataFifo myRecDataFifo.c
